[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# If you want to use Netlify Forms instead of Formspree,
# set netlify={true} and remove 'action' in forms.
# Netlify will detect forms at build time.
